version: '3'

services:
  evo.db.mongo:
    networks: 
      - evodevnetwork
    ports:
      - "27017:27017"
    # volumes:
    #   - "/datadb/:/data/db"
    build:
      context: ./Server/mongo
      dockerfile: Dockerfile

  evo.web.api:
    image: evo.web.api
    networks: 
      - evodevnetwork
    ports:
      - "80:80"
    links: 
      - "evo.db.mongo:db"
    build:
      context: ./Server
      dockerfile: Dockerfile

  evo.web:
    image: evo.web
    build:
      context: ./Client/Angular4Client
      dockerfile: Dockerfile
    ports:
      - "4200:80"

networks: 
  evodevnetwork: 
